version: '3.8'

services:
  grader:
    build:
      context: grader
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./grader:/grader
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env