version: '3.8'

services:
  grader:
    build:
      context: grader
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./grader:/grader
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8080
    env_file:
      - .env